/// Designation dropdown options
class DesignationOptions {
  static const List<String> values = [
    'Trainee',
    'Apprentice',
    'DET (Diploma Engineer Trainee)',
    'GET (Graduate Engineer Trainee)',
    'Operator',
    'Technician',
    'Senior Technician',
    'Team Leader',
    'Line Leader',
    'Analyst',
    'Specialist',
    'Coordinator',
    'Planner',
    'Inspector',
    'Auditor',
    'Supervisor',
    'Executive',
    'Senior Executive',
    'Shift Incharge',
    'Junior Engineer',
    'Engineer',
    'Senior Engineer',
    'Assistant Manager',
    'Deputy Manager',
    'Manager',
    'Senior Manager',
    'AGM (Assistant General Manager)',
    'DGM (Deputy General Manager)',
    'General Manager (GM)',
    'Plant Head',
    'Unit Head',
    'Functional Head',
    'Director',
    'Vice President (VP)',
    'Senior Vice President (SVP)',
    'Chief Executive Officer (CEO)',
    'Chief Operating Officer (COO)',
    'Chief Financial Officer (CFO)',
    'Chief Technology Officer (CTO)',
    'President',
    'Managing Director (MD)',
    'Other designation',
  ];
}
